/*! Open Historia — Discord edition: config loader. © 2026 Nicholas Krol, MIT. */
// Single source of truth read by run.mjs, bot-bridge.mjs and bot.mjs. Holds the
// two secrets (Discord token, AI key) plus non-secret wiring. Generated by the
// installer and gitignored — never commit it.
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const CONFIG_PATH = path.join(__dirname, "..", "discord.config.json");

export const loadConfig = () => {
  if (!existsSync(CONFIG_PATH)) return {};
  // BOM-tolerant: PowerShell's default UTF-8 write prepends a BOM JSON.parse rejects.
  return JSON.parse(readFileSync(CONFIG_PATH, "utf8").replace(/^﻿/, ""));
};

export const CONFIG = loadConfig();

export const ports = {
  game: Number(process.env.GAME_PORT || CONFIG.gamePort || 3000),
  spectator: Number(process.env.SPECTATOR_PORT || CONFIG.spectatorPort || 8080),
  bridge: Number(process.env.BRIDGE_PORT || CONFIG.bridgePort || 8090),
};

// Round timing (seconds), overridable from config.round.
export const timing = {
  votingWindowSec: Number(CONFIG.round?.votingWindowSec || 180),
  interludeSec: Number(CONFIG.round?.interludeSec || 20),
  jumpDays: Number(CONFIG.round?.jumpDays || 30),
};
